"""
Bulk Orphan Linker via Obsidian Graph
======================================
Creates _INDEX.md files in Research_Archives subdirectories
and adds [[wikilinks]] for every orphan in that directory.
"""

from pathlib import Path

MASTER_BRAIN = Path(r"C:\Users\Curtis\New folder\construction-website\Keystone_HQ\00_Master_Brain")
RESEARCH = MASTER_BRAIN / "Research_Archives"

# The subdirectories that contain orphans
subdirs = [
    "04_YT_Analytics",
    "05_Video_Production",
    "07_Coding_Optimization",
    "08_SEO_Website",
]

total_linked = 0

for subdir_name in subdirs:
    subdir = RESEARCH / subdir_name
    if not subdir.exists():
        print(f"SKIP: {subdir_name} does not exist")
        continue
    
    index_path = subdir / "_INDEX.md"
    
    # Get all .md files in this directory (excluding _INDEX itself)
    md_files = sorted([
        f for f in subdir.glob("*.md")
        if f.name != "_INDEX.md"
    ])
    
    if not md_files:
        print(f"SKIP: {subdir_name} has no .md files")
        continue
    
    # Build index content with wikilinks
    lines = [
        f"# {subdir_name.replace('_', ' ')}",
        "",
        f"Research archive index for `{subdir_name}`. Contains {len(md_files)} documents.",
        "",
        "## Documents",
        "",
    ]
    
    for f in md_files:
        stem = f.stem
        # Create a clean display name
        display = stem.replace("_", " ").replace("20260610 ", "").replace("20260522 ", "")
        lines.append(f"- [[{stem}|{display}]]")
        total_linked += 1
    
    lines.append("")
    lines.append("---")
    lines.append("*Auto-generated by orphan_linker_bulk.py*")
    lines.append("")
    
    index_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"OK: {subdir_name} — linked {len(md_files)} files into _INDEX.md")

# Also link each subdirectory _INDEX into the parent Research_Archives/_INDEX
parent_index = RESEARCH / "_INDEX.md"
if parent_index.exists():
    existing = parent_index.read_text(encoding="utf-8", errors="ignore")
    additions = []
    for subdir_name in subdirs:
        link = f"[[{subdir_name}/_INDEX|{subdir_name.replace('_', ' ')}]]"
        if link not in existing:
            additions.append(f"- {link}")
    
    if additions:
        with open(parent_index, "a", encoding="utf-8") as f:
            f.write("\n## Sub-Archives\n\n")
            f.write("\n".join(additions))
            f.write("\n")
        print(f"OK: Linked {len(additions)} sub-indexes into Research_Archives/_INDEX.md")

print(f"\nTotal files linked: {total_linked}")
