// MUSIC_002 — Ana Stevenson DJ Set — 24 Prompts
// IMPORTANT: "Ana" removed from all prompt text to avoid Flow's "prominent people" policy block.
// The character reference image (attached via +Create → Characters → Ana Stevenson → Add to Prompt)
// is what controls her appearance. Her name in the text is redundant and triggers false positives.

const PROMPTS = [
  // A1 — INTRO: Silhouette reveal
  "Pure black screen. A single warm teal spotlight slowly fades up from directly above, gradually illuminating a woman standing behind a Pioneer DJ controller on a minimal black platform. Camera holds a wide shot as light reveals her silhouette. Her hands rest on the edge of the decks. She looks down at the controller. Thin haze drifts slowly through the light beam. Soft steady amber accent from camera-left. She is wearing fitted black leather high-waisted shorts, a dark charcoal ribbed tank top, a slim gold chain necklace, and black chunky rings on both hands. Atmospheric and cinematic. At 0:08, her fingers twitch slightly on the edge of the controller. At 0:09, the camera executes a rapid 1-second whip-pan to the right, dissolving into cinematic motion blur. --no flashing lights --no strobe effects --no watermark --no text artifacts --no subtitles --no floating limbs --no warped face",

  // A2 — Jog wheel touch
  "The video starts with a rapid whip-pan from the right, emerging from motion blur to reveal a woman standing behind a Pioneer DJ controller on a minimal black platform. Pure black background. Camera settles into a medium shot. Single warm teal spotlight from directly above. Soft steady amber accent from camera-left. Thin haze drifts slowly through the light beams. She lifts her right hand and places it gently on the jog wheel. Her head begins to nod once slowly. Her expression is focused and calm. She is wearing fitted black leather high-waisted shorts, a dark charcoal ribbed tank top, a slim gold chain necklace, and black chunky rings on both hands. At 0:08, she glances briefly to her left. At 0:09, the camera executes a rapid 1-second whip-pan to the left, dissolving into cinematic motion blur. --no flashing lights --no strobe effects --no watermark --no text artifacts --no subtitles --no floating limbs --no warped face",

  // A3 — Hands close-up, fader slide
  "The video starts with a rapid whip-pan from the left, emerging from motion blur to reveal a close-up of her hands resting on a Pioneer DJ controller. Pure black background. Minimal black platform. Single warm teal spotlight from directly above. Soft steady amber accent from camera-left. Camera slowly tilts down to frame her fingers as they slide a channel fader up smoothly. Her other hand adjusts an EQ knob with precision. Her black chunky rings catch the teal light. Slow deliberate movements. She is wearing fitted black leather high-waisted shorts, a dark charcoal ribbed tank top, a slim gold chain necklace, and black chunky rings on both hands. At 0:08, her right hand pauses on the fader. At 0:09, the camera executes a rapid 1-second whip-pan tilting upward, dissolving into cinematic motion blur. --no flashing lights --no strobe effects --no watermark --no text artifacts --no subtitles --no floating limbs --no warped face",

  // A4 — Face medium close-up, smirk
  "The video starts with a rapid camera tilt downward, emerging from motion blur to reveal her face in a medium close-up behind a Pioneer DJ controller. Pure black background. Minimal black platform. Single warm teal spotlight from directly above creating soft shadows under her cheekbones. Soft steady amber accent from camera-left. She raises her eyes from the decks and looks straight ahead with a calm confident expression. Her head nods once slowly. The beginning of a smirk forms at the corner of her mouth. She is wearing fitted black leather high-waisted shorts, a dark charcoal ribbed tank top, a slim gold chain necklace. At 0:08, she blinks slowly and her chin lifts slightly. At 0:09, the camera executes a rapid 1-second whip-pan to the right, dissolving into cinematic motion blur. --no flashing lights --no strobe effects --no watermark --no text artifacts --no subtitles --no floating limbs --no warped face",

  // A5 — Relaxed groove, crossfader
  "The video starts with a rapid whip-pan from the right, emerging from motion blur to reveal the woman in a medium shot standing behind a Pioneer DJ controller on a minimal black platform. Pure black background. Single warm teal spotlight from directly above. Soft steady amber accent from camera-left. Thin haze drifts slowly through the light beams. Her eyes are half-closed and her head moves side to side gently with an internal rhythm. Her right hand rests on the crossfader. Her gold chain necklace glints in the teal light. Relaxed and in control. She is wearing fitted black leather high-waisted shorts, a dark charcoal ribbed tank top, a slim gold chain necklace, and black chunky rings on both hands. At 0:08, she opens her eyes fully and looks down at her hands. At 0:09, the camera executes a rapid 1-second whip-pan to the left, dissolving into cinematic motion blur. --no flashing lights --no strobe effects --no watermark --no text artifacts --no subtitles --no floating limbs --no warped face",

  // A6 — Building energy, hot cues
  "The video starts with a rapid whip-pan from the left, emerging from motion blur to reveal the woman in a medium shot behind a Pioneer DJ controller on a minimal black platform. Pure black background. Camera slowly pushes in from medium to medium-close. Single warm teal spotlight from directly above. Soft steady amber accent from camera-left. Her left hand slides the crossfader smoothly from one side to the other while her right hand hovers over the hot cue buttons. She bobs her head to a rhythm with slightly more energy now. Haze drifts around her shoulders. She is wearing fitted black leather high-waisted shorts, a dark charcoal ribbed tank top, a slim gold chain necklace, and black chunky rings on both hands. At 0:08, her right hand drops to press a cue button. At 0:09, the camera executes a rapid 1-second whip-pan to the right, dissolving into cinematic motion blur. --no flashing lights --no strobe effects --no watermark --no text artifacts --no subtitles --no floating limbs --no warped face",

  // A7 — Headphone cue listen
  "The video starts with a rapid whip-pan from the right, emerging from motion blur to reveal the woman in a medium shot behind a Pioneer DJ controller on a minimal black platform. Pure black background. Single warm teal spotlight from directly above. Soft steady amber accent from camera-left. She reaches up with her right hand and presses one headphone cup gently against her ear while tilting her head to the side. Her left hand stays on the mixer. Her eyes are focused and intense, listening. Haze catches the light above her. She is wearing fitted black leather high-waisted shorts, a dark charcoal ribbed tank top, a slim gold chain necklace, and black chunky rings on both hands. At 0:08, she nods once as if confirming the beat is right. At 0:09, the camera executes a rapid 1-second whip-pan tilting downward, dissolving into cinematic motion blur. --no flashing lights --no strobe effects --no watermark --no text artifacts --no subtitles --no floating limbs --no warped face",

  // A8 — Headphone drop, both hands on mixer
  "The video starts with a rapid camera tilt upward, emerging from motion blur to reveal the woman in a medium-close shot behind a Pioneer DJ controller on a minimal black platform. Pure black background. Single warm teal spotlight from directly above. Soft steady amber accent from camera-left. She drops the headphone from her ear back around her neck with a smooth casual motion. She immediately brings both hands to the mixer. Her head nods forward once with purpose. Camera holds steady. A subtle satisfied smirk appears. She is wearing fitted black leather high-waisted shorts, a dark charcoal ribbed tank top, a slim gold chain necklace, and black chunky rings on both hands. At 0:08, she settles deeper into her stance behind the decks. At 0:09, the camera executes a rapid 1-second whip-pan to the left, dissolving into cinematic motion blur. --no flashing lights --no strobe effects --no watermark --no text artifacts --no subtitles --no floating limbs --no warped face",

  // A9 — Camera orbit, confident mixing
  "The video starts with a rapid whip-pan from the left, emerging from motion blur to reveal the woman in a medium shot behind a Pioneer DJ controller on a minimal black platform. Pure black background. Single warm teal spotlight from directly above. Soft steady amber accent from camera-left. Camera slowly moves around her from front to her right side in a smooth continuous arc. Both hands work the mixer with confident movements. Her body sways slightly with the beat. Thin haze drifts through the teal light beam. She is wearing fitted black leather high-waisted shorts, a dark charcoal ribbed tank top, a slim gold chain necklace, and black chunky rings on both hands. At 0:08, she glances toward the camera as it passes. At 0:09, the camera executes a rapid 1-second whip-pan continuing to the right, dissolving into cinematic motion blur. --no flashing lights --no strobe effects --no watermark --no text artifacts --no subtitles --no floating limbs --no warped face",

  // A10 — Extreme close-up, FX knob
  "The video starts with a rapid whip-pan from the right, emerging from motion blur to reveal an extreme close-up of her right hand on a Pioneer DJ controller. Pure black background. Single warm teal spotlight from directly above illuminating her fingers. Her fingers grip and slowly turn the FX knob with precision. Her black chunky rings catch the light. Camera holds tight on the hand movement for the full clip. Soft steady amber accent from camera-left. She is wearing fitted black leather high-waisted shorts, a dark charcoal ribbed tank top, a slim gold chain necklace, and black chunky rings on both hands. At 0:08, her thumb lifts slightly off the knob. At 0:09, the camera executes a rapid 1-second whip-pan tilting upward, dissolving into cinematic motion blur. --no flashing lights --no strobe effects --no watermark --no text artifacts --no subtitles --no floating limbs --no warped face",

  // A11 — Eyes closed, absorbed in music
  "The video starts with a rapid camera tilt downward, emerging from motion blur to reveal her face in a close-up behind a Pioneer DJ controller on a minimal black platform. Pure black background. Single warm teal spotlight from directly above. Soft steady amber accent from camera-left. Her eyes are closed. She is completely absorbed in the music. Her head moves with natural intensity and her shoulders roll gently with the beat. Shadows shift subtly across her face as she moves. She is wearing fitted black leather high-waisted shorts, a dark charcoal ribbed tank top, a slim gold chain necklace. At 0:08, her lips press together slightly. At 0:09, the camera executes a rapid 1-second whip-pan to the right, dissolving into cinematic motion blur. --no flashing lights --no strobe effects --no watermark --no text artifacts --no subtitles --no floating limbs --no warped face",

  // A12 — Fierce direct stare
  "The video starts with a rapid whip-pan from the right, emerging from motion blur to reveal her face in a close-up behind a Pioneer DJ controller on a minimal black platform. Pure black background. Single warm teal spotlight from directly above creating a sharp shadow on one side of her face. Her eyes snap open and she looks directly into the camera lens with calm fierce intensity. She holds the stare without blinking. Her right hand reaches down to the mixer below frame. Camera holds perfectly still. She is wearing fitted black leather high-waisted shorts, a dark charcoal ribbed tank top, a slim gold chain necklace. At 0:08, her jaw tightens almost imperceptibly. At 0:09, the camera executes a rapid 1-second whip-pan to the left, dissolving into cinematic motion blur. --no flashing lights --no strobe effects --no watermark --no text artifacts --no subtitles --no floating limbs --no warped face",

  // A13 — Wide shot, building energy
  "The video starts with a rapid whip-pan from the left, emerging from motion blur to reveal the woman in a wide shot behind a Pioneer DJ controller on a minimal black platform. Pure black background. Camera slowly pushes in from wide toward medium. Single warm teal spotlight from directly above. Soft steady amber accent from camera-left. Thin haze thickens slightly around her. Both her hands move across the decks with faster more confident movements. Her head bobs with building energy. The wide shot shows the full dramatic scale of the minimal booth against pure black. She is wearing fitted black leather high-waisted shorts, a dark charcoal ribbed tank top, a slim gold chain necklace, and black chunky rings on both hands. At 0:08, she shifts her weight forward leaning into the decks. At 0:09, the camera executes a rapid 1-second whip-pan to the right, dissolving into cinematic motion blur. --no flashing lights --no strobe effects --no watermark --no text artifacts --no subtitles --no floating limbs --no warped face",

  // A14 — Breath pause, anticipation
  "The video starts with a rapid whip-pan from the right, emerging from motion blur to reveal the woman in a medium-close shot behind a Pioneer DJ controller on a minimal black platform. Pure black background. Single warm teal spotlight from directly above. Soft steady amber accent from camera-left. She pauses for a beat. Both hands rest flat on the mixer. She takes a slow deliberate breath. Camera holds steady on her face. Her expression is one of focused anticipation. Complete control. She is wearing fitted black leather high-waisted shorts, a dark charcoal ribbed tank top, a slim gold chain necklace. At 0:08, her fingers curl slightly on the mixer edge. At 0:09, the camera executes a rapid 1-second whip-pan to the left, dissolving into cinematic motion blur. --no flashing lights --no strobe effects --no watermark --no text artifacts --no subtitles --no floating limbs --no warped face",

  // A15 — Sharp precise mixing, confident smirk
  "The video starts with a rapid whip-pan from the left, emerging from motion blur to reveal the woman in a medium shot behind a Pioneer DJ controller on a minimal black platform. Pure black background. Single warm teal spotlight from directly above. Soft steady amber accent from camera-left. She brings both hands decisively onto the controller and begins working the mixer with sharp precise movements. Camera slowly pushes in from medium to medium-close. Her head nods with authority. Her expression shifts to a subtle confident smirk. Maximum energy but complete control. She is wearing fitted black leather high-waisted shorts, a dark charcoal ribbed tank top, a slim gold chain necklace, and black chunky rings on both hands. At 0:08, she lifts her chin slightly. At 0:09, the camera executes a rapid 1-second whip-pan to the right, dissolving into cinematic motion blur. --no flashing lights --no strobe effects --no watermark --no text artifacts --no subtitles --no floating limbs --no warped face",

  // A16 — Wide shot, full performance mode
  "The video starts with a rapid whip-pan from the right, emerging from motion blur to reveal the woman in a wide shot behind a Pioneer DJ controller on a minimal black platform. Pure black background. Camera holds the wide shot showing the full booth and figure. Single warm teal spotlight from directly above. Soft steady amber accent from camera-left. Thick haze drifts through the light beams. She is in full performance mode with her hands moving fluidly across the mixer. Her body moves with aggressive controlled energy. She owns the space. She is wearing fitted black leather high-waisted shorts, a dark charcoal ribbed tank top, a slim gold chain necklace, and black chunky rings on both hands. At 0:08, she glances up from the decks directly at the camera. At 0:09, the camera executes a rapid 1-second whip-pan to the left, dissolving into cinematic motion blur. --no flashing lights --no strobe effects --no watermark --no text artifacts --no subtitles --no floating limbs --no warped face",

  // A17 — Camera orbit, fierce eye contact
  "The video starts with a rapid whip-pan from the left, emerging from motion blur to reveal the woman in a medium shot behind a Pioneer DJ controller on a minimal black platform. Pure black background. Camera smoothly moves around her from left to right in a continuous slow arc. Single warm teal spotlight from directly above follows as the camera moves. Soft steady amber accent shifts as the angle changes. As the camera passes in front of her she locks eyes with the lens with a fierce composed expression. Her hands never stop moving on the decks. Cinematic and powerful. She is wearing fitted black leather high-waisted shorts, a dark charcoal ribbed tank top, a slim gold chain necklace, and black chunky rings on both hands. At 0:08, she breaks eye contact and looks back down at the decks. At 0:09, the camera executes a rapid 1-second whip-pan continuing to the right, dissolving into cinematic motion blur. --no flashing lights --no strobe effects --no watermark --no text artifacts --no subtitles --no floating limbs --no warped face",

  // A18 — Profile shot, EQ adjust
  "The video starts with a rapid whip-pan from the right, emerging from motion blur to reveal the woman in a medium-close shot from slightly camera-right behind a Pioneer DJ controller on a minimal black platform. Pure black background. Single warm teal spotlight from directly above. Soft steady amber accent from camera-left catches her profile. She leans forward slightly into the decks, one hand adjusting the high EQ while the other holds the crossfader. Her chin drops and she watches her own hands work with total focus. Camera slowly pushes in. Her gold chain hangs forward. She is wearing fitted black leather high-waisted shorts, a dark charcoal ribbed tank top, a slim gold chain necklace, and black chunky rings on both hands. At 0:08, she tilts her head slightly to one side. At 0:09, the camera executes a rapid 1-second whip-pan to the left, dissolving into cinematic motion blur. --no flashing lights --no strobe effects --no watermark --no text artifacts --no subtitles --no floating limbs --no warped face",

  // A19 — Peak confidence, knowing smirk
  "The video starts with a rapid whip-pan from the left, emerging from motion blur to reveal the woman in a medium shot behind a Pioneer DJ controller on a minimal black platform. Pure black background. Single warm teal spotlight from directly above. Soft steady amber accent from camera-left. Camera holds steady. Both hands work the mixer with fluid practiced movements. She looks up from the decks and stares directly into the camera with an intense knowing smirk. She is completely in her element. Peak confidence. Camera slowly pushes in to medium-close. She is wearing fitted black leather high-waisted shorts, a dark charcoal ribbed tank top, a slim gold chain necklace, and black chunky rings on both hands. At 0:08, she gives the slightest nod to camera. At 0:09, the camera executes a rapid 1-second whip-pan to the right, dissolving into cinematic motion blur. --no flashing lights --no strobe effects --no watermark --no text artifacts --no subtitles --no floating limbs --no warped face",

  // A20 — Calm rhythm, found her stride
  "The video starts with a rapid whip-pan from the right, emerging from motion blur to reveal the woman in a medium shot behind a Pioneer DJ controller on a minimal black platform. Pure black background. Single warm teal spotlight from directly above. Soft steady amber accent from camera-left. Camera holds steady at medium distance. Her expression is calm and satisfied. Her head nods rhythmically at a steady pace. She looks down at the decks briefly then back up with a slight knowing smile. She has found her stride. Thin haze drifts gently. She is wearing fitted black leather high-waisted shorts, a dark charcoal ribbed tank top, a slim gold chain necklace, and black chunky rings on both hands. At 0:08, she exhales visibly and her shoulders drop slightly in relaxation. At 0:09, the camera executes a rapid 1-second whip-pan to the left, dissolving into cinematic motion blur. --no flashing lights --no strobe effects --no watermark --no text artifacts --no subtitles --no floating limbs --no warped face",

  // A21 — Professional crossfader transition
  "The video starts with a rapid whip-pan from the left, emerging from motion blur to reveal the woman in a medium shot behind a Pioneer DJ controller on a minimal black platform. Pure black background. Camera slowly pulls back from medium to medium-wide. Single warm teal spotlight from directly above. Soft steady amber accent from camera-left. Her left hand slides the crossfader while her right hand reaches across to adjust the incoming channel EQ. The movement is fluid and practiced. Professional and effortless. She is wearing fitted black leather high-waisted shorts, a dark charcoal ribbed tank top, a slim gold chain necklace, and black chunky rings on both hands. At 0:08, she finishes the transition and both hands settle on the mixer. At 0:09, the camera executes a rapid 1-second whip-pan to the right, dissolving into cinematic motion blur. --no flashing lights --no strobe effects --no watermark --no text artifacts --no subtitles --no floating limbs --no warped face",

  // A22 — Quiet approval, renewed energy
  "The video starts with a rapid whip-pan from the right, emerging from motion blur to reveal the woman in a medium shot behind a Pioneer DJ controller on a minimal black platform. Pure black background. Single warm teal spotlight from directly above. Soft steady amber accent from camera-left. She finishes a mix transition and nods once to herself in quiet approval. She rolls her shoulders once then leans back into the decks with renewed easy energy. Camera holds steady. She glances to camera-left briefly as if acknowledging someone then looks back to the decks with a half-smile. She is wearing fitted black leather high-waisted shorts, a dark charcoal ribbed tank top, a slim gold chain necklace, and black chunky rings on both hands. At 0:08, her gaze returns to center. At 0:09, the camera executes a rapid 1-second whip-pan to the left, dissolving into cinematic motion blur. --no flashing lights --no strobe effects --no watermark --no text artifacts --no subtitles --no floating limbs --no warped face",

  // A23 — Wind down, light dims
  "The video starts with a rapid whip-pan from the left, emerging from motion blur to reveal the woman in a medium shot behind a Pioneer DJ controller on a minimal black platform. Pure black background. Camera slowly pulls back from medium to wide. Single warm teal spotlight from directly above begins to dim very gradually. Soft steady amber accent from camera-left softens. She makes one last smooth adjustment to the mixer and lets the track ride. She takes one hand off the controller and rests it on the edge of the booth. Her head still nods gently. The energy is winding down naturally. She is wearing fitted black leather high-waisted shorts, a dark charcoal ribbed tank top, a slim gold chain necklace, and black chunky rings on both hands. At 0:08, her remaining hand lifts from the mixer. At 0:09, the camera executes a rapid 1-second whip-pan to the right, dissolving into cinematic motion blur. --no flashing lights --no strobe effects --no watermark --no text artifacts --no subtitles --no floating limbs --no warped face",

  // A24 — OUTRO: Fade to black
  "The video starts with a rapid whip-pan from the right, emerging from motion blur to reveal the woman in a wide shot standing behind a Pioneer DJ controller on a minimal black platform. Pure black background. Single warm teal spotlight from directly above is dim. Soft amber accent is barely visible. She lifts both hands off the controller and lets them rest at her sides. She looks up from the decks directly into the camera with a calm powerful stare. The teal spotlight slowly dims further. Her silhouette becomes darker and darker. She gives one final slow nod. The light fades until only the faintest outline of her face is visible against pure black. No subtitles. --no flashing lights --no strobe effects --no watermark --no text artifacts --no subtitles --no floating limbs --no warped face",
];